defaults: &defaults
  url: "amqp://localhost:5672"
  exchange_name: "psd.s2"
  durable: true
  message_persistent: true
  prefetch_number: 1
  heart_beat: 0

test:
  <<: *defaults
  exchange_name: "psd.s2.test"
  durable: false
  message_persistent: false

development:
  <<: *defaults

